export enum CompetitionType {
  EASV_WORLDCUP = 'EASV_WORLDCUP',
  EASV_STAENDEMATCH = 'EASV_STAENDEMATCH',
  EASV_VERBAENDEFINAL = 'EASV_VERBAENDEFINAL',
  ZSAV_NAWU = 'ZSAV_NAWU',
  ZSAV_NAWU_GM = 'ZSAV_NAWU_GM',
  EASV_NAWU_GM = 'EASV_NAWU_GM',
  ZSAV = 'ZSAV',
  EASV_SM_10M = 'EASV_SM_10M',
}
